# Пропишем версию
version: '3.3'
# Перечислим сервисы
services:
    nginx:
# Пропишем какой образ мы хотим использовать
        image: nginx:latest
# Назовем свой контейнер по красивому
        container_name: nginx
# Проброс портов
        ports:
            - "80:80"
            - "443:443"
# Проброс папок
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./nginx/www:/var/www/
            - ./nginx/Logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
# Укажем зависимости
        links:
            - php


    php:
# Билдим с помощью dockerfile указав директорию где он лежит
        build:
            context: ./php
            dockerfile: DockerFile

        container_name: php-fpm

        volumes:
            - ./nginx/www:/var/www
